version: '3.8'

services:
  portfolio:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: portfolio
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/local.ini
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    tty: true
    ports:
      - 2088:2088
    networks:
      - portfolio-network
  portfolio_nginx:
    image: nginx:alpine
    container_name: portfolio_nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      - 8000:80
    networks:
      - portfolio-network
    depends_on:
      - portfolio
      - portfolio_db
  portfolio_cache:
    image: redis:alpine
    container_name: portfolio_cache
    restart: unless-stopped
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/data:/data
      - portfolio_cache:/data
    tty: true
    ports:
      - 6379:6379
    networks:
      - portfolio-network
    depends_on:
      - portfolio
  portfolio_db:
    image: postgres:13-alpine
    container_name: portfolio_db
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - portfolio_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio_db
    networks:
      - portfolio-network
  portfolio_adminer:
    image: adminer
    container_name: portfolio_adminer
    restart: unless-stopped
    tty: true
    environment:
      ADMINER_DEFAULT_SERVER: portfolio_db
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 8080:8080
    networks:
      - portfolio-network
    depends_on:
      - portfolio_db

volumes:
  portfolio_cache:
  portfolio_db:

networks:
  portfolio-network: